  [build]
  command = "node server.js"
  functions = "build/"
  environment = { PORT = "4726", MONGO_URI = "mongodb+srv://usermain0:zH0iq7DFFbfC0XiX@cluster0.sakalik.mongodb.net/?retryWrites=true&w=majority", API_KEY = "tvytfrvy64yciubnmou98it76d454" }

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200